### ISSUE TITLE
Individual HTML tag colors not applied

### ISSUE THREAD

**Issue by djvern** [mghweb/SublimeDreamweaver#1]
I've just installed this color theme by following your instructions in the README file. However I can't get individual html tags working, such as img and a. I've replaced the HTML.tmLanguage file in Packages/HTML - is that correct? You mention a 'Data' folder but I don't have any such folder (I'm running Sublime Text 2.0.2 on OSX).

Any help would be greatly appreciated - I'm transitioning from Dreamweaver so this color scheme is a great help!

**Comment by mghdotdev** [comment]
On the Mac version it should be located in...

~/Library/Application Support/Sublime Text 2/Packages/HTML/HTML.tmLanguage

Also don't forget to apply the Javacript one as well to get a "closer to dream weaver" experience as well.

I just transitioned a few months ago, trust me its worth it! Sublime is amazing.

**Comment by timbouchard** [comment]
I think djvern is onto something here. I noticed how great this theme was until I hit the HTML guts of the pages I was working on. It's workable right now, but would be amazing if the purples and oranges worked.

I tried going into the .theme file and saw all the XML which looked legit and I also looked at the HTML.tmLanguage and see both the "IMG" and "input/textarea/label/button/form/legend/fieldset" both look ssetup correctly. I can't figure out why or where the connection is being dropped.

The theme looks real promising.

Any idea why it would do that?

![mghdw-html-bug](https://f.cloud.github.com/assets/2424927/1017938/83001e2e-0c1c-11e3-9a0e-e48f5a41283b.jpg)

**Comment by sergesaveliev** [comment]
Here’s how I've made it work with SublimeText 3:
1. Place ‘mghDreamweaver.tmTheme’ into ~/Library/Application Support/Sublime Text 3/Packages/User folder.
2. Place ‘HTML.tmLanguage’ into ~/Library/Application Support/Sublime Text 3/Cache/HTML folder.
3. Place ‘JavaScript.tmLanguage’ into ~/Library/Application Support/Sublime Text 3/Cache/JavaScript folder.

Hope it'll help.

**Comment by Paul-Hume** [comment]
Hi there,

I am using Sublime Text 2 on OSX and installed both the HTML Language file and the Javascript file but the HTML colour coding doesn't seem to be working for me? All of the colours in the PHP sections of the code are pretty spot on for Dreamweaver but the HTML tags such as IMG, INPUT etc are all the same blue colour. 

Is there a way of getting this to work? Thanks in advance for any help you can offer.

Paul

**Comment by Paul-Hume** [comment]
Hi there, 

An update on my last message, I have updated my OSX and installed Sublime Text 3 and followed Sergesaveliev instructions. I still don't get the text highlighting on IMG, INPUT etc only highlighting on the PHP code.

![sublime](https://cloud.githubusercontent.com/assets/5228593/2900136/bd889222-d5c2-11e3-8719-e9f13a274281.jpg)

I am really enjoying using Sublime and thought that this theme would be a perfect transition from my trusty Dreamweaver. I would really appreciate any help in making the highlights work correctly.

Thanks in advance for any help.

Paul

**Comment by sergesaveliev** [comment]
Here’s the update to my instruction above on how to make it work with SublimeText 3.

I've just installed the theme on my other mac using a slightly different way:
1. Place ‘mghDreamweaver’ folder into ~/Library/Application Support/Sublime Text 3/Packages/ folder.
2. There were no 'HTML' and 'JavaScript' folders in '~/Library/Application Support/Sublime Text 3/Packages/' folder originally, so I've created both folders and put ‘HTML.tmLanguage’ and ‘JavaScript.tmLanguage’ into them respectively. 

Now it works well with all tags including A, IMG, INPUT etc.

UPDATE: Add "HTML" to "ignored_packages" in Preferences > Settings User:
![screen shot 2014-06-25 at 10 22 17 am](https://cloud.githubusercontent.com/assets/3211073/3388849/4f7d62ca-fc8d-11e3-8c0d-887447987d7c.png)

**Comment by djvern** [comment]
Thanks mghweb and sergesaveliev, I've moved onto Sublime Text 3 now and these instructions work perfectly!

**Comment by Paul-Hume** [comment]
I've just come back to this after briefly resorting back to Dreamweaver because I found this a little frustrating. I have just done the update Sergesaveliev put and it's working brilliantly.

Thanks for finding a solution.

**Comment by Paul-Hume** [comment]
Hi there, 

I use this at work on Mac and as said previously, I have tried installing it on my PC at home and can't get it to work, any suggestions would be appreciated.

Thanks

Paul

**Comment by Paul-Hume** [comment]
Ooops, spoke to soon, I found the correct place to put them.
